name: PR-Build

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Setup secrets
        shell: bash
        run: echo "${{secrets.PRIVATE_YML}}" > src/main/resources/application-private.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Test with Gradle
        run: ./gradlew test